/** UFs brasileiras para selects (IBGE id + nome + UF). */
export const ESTADOS_BRASIL = [
  { id: 12, nome: "Acre", uf: "AC" },
  { id: 27, nome: "Alagoas", uf: "AL" },
  { id: 16, nome: "Amapá", uf: "AP" },
  { id: 13, nome: "Amazonas", uf: "AM" },
  { id: 29, nome: "Bahia", uf: "BA" },
  { id: 23, nome: "Ceará", uf: "CE" },
  { id: 53, nome: "Distrito Federal", uf: "DF" },
  { id: 32, nome: "Espírito Santo", uf: "ES" },
  { id: 52, nome: "Goiás", uf: "GO" },
  { id: 21, nome: "Maranhão", uf: "MA" },
  { id: 51, nome: "Mato Grosso", uf: "MT" },
  { id: 50, nome: "Mato Grosso do Sul", uf: "MS" },
  { id: 31, nome: "Minas Gerais", uf: "MG" },
  { id: 15, nome: "Pará", uf: "PA" },
  { id: 25, nome: "Paraíba", uf: "PB" },
  { id: 41, nome: "Paraná", uf: "PR" },
  { id: 26, nome: "Pernambuco", uf: "PE" },
  { id: 22, nome: "Piauí", uf: "PI" },
  { id: 33, nome: "Rio de Janeiro", uf: "RJ" },
  { id: 24, nome: "Rio Grande do Norte", uf: "RN" },
  { id: 43, nome: "Rio Grande do Sul", uf: "RS" },
  { id: 11, nome: "Rondônia", uf: "RO" },
  { id: 14, nome: "Roraima", uf: "RR" },
  { id: 42, nome: "Santa Catarina", uf: "SC" },
  { id: 35, nome: "São Paulo", uf: "SP" },
  { id: 28, nome: "Sergipe", uf: "SE" },
  { id: 17, nome: "Tocantins", uf: "TO" },
] as const
