// Catálogo estático dos Enxames (seed/fallback da vitrine).
// O backend (/api/enxames) é a fonte autoritativa; este seed garante que a UI
// nunca quebre offline. Nomes de tipo/const seguem "Machine*" por legado interno
// — o conceito visível ao usuário é "Enxame".
// O slug do enxame é dinâmico (criado/editado via admin, vem do backend).
// Tipado como string ampla — os 15 slugs seed estão em MACHINES abaixo.
export type MachineId = string

export type MachineTheme = {
  id: MachineId
  name: string
  label: string
  headline: string
  subheadline: string
  microcopy: string
  inputPlaceholder: string
  rotatingPlaceholders: string[]
  ctaLabel: string
  processingSteps: string[]
  resultCards: { title: string; tag?: string }[]
  keywords: string[]
  colors: {
    from: string
    to: string
    glow: string
    ring: string
    accent: string
    text: string
  }
}

export const MACHINES: MachineTheme[] = [
  {
    id: "marketing",
    name: "Enxame de Marketing",
    label: "01",
    headline: "Transforme sua marca em presença.",
    subheadline:
      "Estrategistas, designers e criadores para fazer seu marketing vender de verdade.",
    microcopy: "Da estratégia à execução: o time que faz sua marca crescer.",
    inputPlaceholder: "Quero crescer minha marca",
    rotatingPlaceholders: [
      "quero mais clientes",
      "quero uma identidade visual",
      "quero gestão de redes",
      "quero conteúdo que vende",
    ],
    ctaLabel: "Ativar enxame de marketing",
    processingSteps: [
      "analisando sua marca...",
      "cruzando especialistas...",
      "montando seu time de marketing...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Estrategista de Marketing e Gestão" },
      { title: "Social Media" },
      { title: "Copywriter" },
      { title: "Designer Gráfico" },
      { title: "Editor de Vídeo" },
      { title: "Videomaker" },
      { title: "Fotógrafo" },
      { title: "Web Designer" },
      { title: "Atendimento ao Cliente" },
      { title: "Criador de Conteúdo" },
      { title: "Contador" },
      { title: "Gestor" },
      { title: "Administrador" },
    ],
    keywords: ["marketing", "conteúdo", "design", "gestão"],
    colors: {
      from: "#e11d48",
      to: "#f43f5e",
      glow: "rgba(244,63,94,0.45)",
      ring: "rgba(244,63,94,0.7)",
      accent: "#fb7185",
      text: "#fecdd3",
    },
  },
  {
    id: "tecnologia",
    name: "Enxame de Tecnologia",
    label: "02",
    headline: "Construa o que sua ideia precisa.",
    subheadline:
      "Desenvolvedores, engenheiros e especialistas em dados e IA para tirar projetos do papel.",
    microcopy: "Do protótipo ao deploy: tecnologia com gente que entrega.",
    inputPlaceholder: "Quero desenvolver meu sistema",
    rotatingPlaceholders: [
      "quero um app",
      "quero um site",
      "quero automação",
      "quero integrar IA",
    ],
    ctaLabel: "Ativar enxame de tecnologia",
    processingSteps: [
      "interpretando o projeto...",
      "buscando devs e engenheiros...",
      "combinando stacks...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Desenvolvedor/Programador" },
      { title: "Engenheiro de Software" },
      { title: "Analista de Sistemas" },
      { title: "QA / Tester" },
      { title: "DevOps" },
      { title: "DBA" },
      { title: "Engenheiro de Dados" },
      { title: "Especialista em IA" },
      { title: "Suporte Técnico" },
      { title: "Web Designer" },
      { title: "Gerente de Projetos" },
      { title: "Engenheiro de Infraestrutura" },
      { title: "Cybersegurança" },
    ],
    keywords: ["software", "dados", "IA", "infraestrutura"],
    colors: {
      from: "#2563eb",
      to: "#3b82f6",
      glow: "rgba(59,130,246,0.45)",
      ring: "rgba(59,130,246,0.7)",
      accent: "#60a5fa",
      text: "#bfdbfe",
    },
  },
  {
    id: "transporte",
    name: "Enxame de Transporte",
    label: "03",
    headline: "Mova pessoas e cargas sem atrito.",
    subheadline:
      "Motoristas, entregadores e logística para tudo chegar no lugar certo.",
    microcopy: "Da entrega rápida à mudança completa: transporte na hora.",
    inputPlaceholder: "Preciso de transporte",
    rotatingPlaceholders: [
      "preciso de um motoboy",
      "quero fazer uma mudança",
      "preciso de entrega hoje",
      "quero um motorista",
    ],
    ctaLabel: "Ativar enxame de transporte",
    processingSteps: [
      "analisando a rota...",
      "localizando profissionais próximos...",
      "priorizando agilidade...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Motorista de Aplicativo" },
      { title: "Motorista Particular" },
      { title: "Motoboy" },
      { title: "Entregador de Aplicativo" },
      { title: "Caminhoneiro" },
      { title: "Gerente de Logística" },
      { title: "Operador de Logística" },
      { title: "Operador de Empilhadeira" },
      { title: "Expedidor" },
      { title: "Transportadora de Mudanças" },
      { title: "Ajudante de Mudança" },
      { title: "Montador de Móveis para Mudança" },
      { title: "Transporte Escolar" },
      { title: "Entregador de Bicicleta" },
      { title: "Refrigerado" },
    ],
    keywords: ["entrega", "mudança", "logística", "motorista"],
    colors: {
      from: "#d97706",
      to: "#f59e0b",
      glow: "rgba(245,158,11,0.45)",
      ring: "rgba(245,158,11,0.7)",
      accent: "#fbbf24",
      text: "#fde68a",
    },
  },
  {
    id: "artistas",
    name: "Enxame de Artistas",
    label: "04",
    headline: "Dê palco para o seu projeto.",
    subheadline:
      "Músicos, atores, ilustradores e performers para dar vida a qualquer ideia.",
    microcopy: "Talento que transforma ideia em arte.",
    inputPlaceholder: "Quero contratar um artista",
    rotatingPlaceholders: [
      "quero um cantor para meu evento",
      "quero uma ilustração",
      "procuro um DJ",
      "quero um ator",
    ],
    ctaLabel: "Ativar enxame de artistas",
    processingSteps: [
      "entendendo o projeto...",
      "cruzando talentos...",
      "selecionando artistas...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Cantor" },
      { title: "Instrumentista" },
      { title: "Compositor" },
      { title: "Produtor Musical" },
      { title: "DJ" },
      { title: "Ator/Atriz" },
      { title: "Dublador" },
      { title: "Roteirista" },
      { title: "Comediante" },
      { title: "Apresentador" },
      { title: "Dançarino" },
      { title: "Modelo Fotográfico" },
      { title: "Ilustrador" },
      { title: "Tatuador" },
      { title: "Artista Digital" },
      { title: "Artista Plástico" },
      { title: "Artista de Rua" },
      { title: "Artista Circense" },
      { title: "Figurinista" },
      { title: "Professor de Artes" },
      { title: "Estilista" },
    ],
    keywords: ["música", "arte", "palco", "performance"],
    colors: {
      from: "#7c3aed",
      to: "#a855f7",
      glow: "rgba(168,85,247,0.45)",
      ring: "rgba(168,85,247,0.7)",
      accent: "#c084fc",
      text: "#e9d5ff",
    },
  },
  {
    id: "justica",
    name: "Enxame de Justiça",
    label: "05",
    headline: "Defenda causas com quem entende.",
    subheadline:
      "Advogados, jornalistas, servidores e atuação pública para causas e instituições.",
    microcopy: "Direito, política e voz pública num só lugar.",
    inputPlaceholder: "Preciso de apoio jurídico",
    rotatingPlaceholders: [
      "preciso de um advogado",
      "quero assessoria",
      "procuro um consultor político",
      "preciso de apoio institucional",
    ],
    ctaLabel: "Ativar enxame de justiça",
    processingSteps: [
      "analisando a demanda...",
      "buscando especialistas...",
      "combinando áreas de atuação...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Político de Carreira" },
      { title: "Presidente da República" },
      { title: "Secretário" },
      { title: "Assessor" },
      { title: "Cientista Político" },
      { title: "Marqueteiro Político" },
      { title: "Servidor Público" },
      { title: "Advogado" },
      { title: "Juiz" },
      { title: "Delegado" },
      { title: "Fiscal" },
      { title: "Jornalista" },
      { title: "Ativista" },
      { title: "Sindicalista" },
      { title: "Militante Político" },
      { title: "Conselheiro" },
      { title: "Relações Institucionais" },
    ],
    keywords: ["direito", "política", "instituições", "causas"],
    colors: {
      from: "#4338ca",
      to: "#6366f1",
      glow: "rgba(99,102,241,0.45)",
      ring: "rgba(99,102,241,0.7)",
      accent: "#818cf8",
      text: "#c7d2fe",
    },
  },
  {
    id: "influencer",
    name: "Enxame de Influencer",
    label: "06",
    headline: "Conecte sua marca com audiências reais.",
    subheadline:
      "Creators de todos os nichos para divulgar, engajar e gerar alcance.",
    microcopy: "Não é só alcance. É a audiência certa.",
    inputPlaceholder: "Quero divulgar com creators",
    rotatingPlaceholders: [
      "quero influenciadores do meu nicho",
      "quero uma campanha",
      "procuro um creator UGC",
      "quero mais alcance",
    ],
    ctaLabel: "Ativar enxame de influencer",
    processingSteps: [
      "analisando o público-alvo...",
      "cruzando nichos e audiência...",
      "selecionando creators...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Streamer" },
      { title: "YouTuber" },
      { title: "Tiktoker" },
      { title: "Instagrammer" },
      { title: "Podcaster" },
      { title: "Gamer" },
      { title: "Fitness" },
      { title: "Moda/Beleza" },
      { title: "Tecnologia" },
      { title: "Viagem" },
      { title: "Gastronômico" },
      { title: "Automotivo" },
      { title: "Geek" },
      { title: "Stand-up" },
      { title: "Educacional" },
      { title: "Negócios" },
      { title: "Financeiro" },
      { title: "Coach" },
      { title: "Música" },
      { title: "Dança" },
      { title: "Cinema/Séries" },
      { title: "Futebol" },
      { title: "Esportes" },
      { title: "Pet" },
      { title: "Biólogo" },
      { title: "Afiliado Digital" },
      { title: "Luxo" },
      { title: "Conteúdo Adulto" },
      { title: "Relacionamento" },
      { title: "Maternidade" },
      { title: "Saúde" },
      { title: "Decoração" },
      { title: "Cosplayer" },
    ],
    keywords: ["creators", "alcance", "nicho", "campanha"],
    colors: {
      from: "#db2777",
      to: "#ec4899",
      glow: "rgba(236,72,153,0.45)",
      ring: "rgba(236,72,153,0.7)",
      accent: "#f472b6",
      text: "#fbcfe8",
    },
  },
  {
    id: "servicos_residenciais",
    name: "Enxame de Serviços Residenciais",
    label: "07",
    headline: "Resolva a casa sem dor de cabeça.",
    subheadline:
      "Limpeza, cuidados, manutenção e apoio para o dia a dia do seu lar.",
    microcopy: "Rápido, direto e sem complicação.",
    inputPlaceholder: "Preciso de ajuda em casa",
    rotatingPlaceholders: [
      "preciso de uma diarista",
      "quero um jardineiro",
      "preciso de um chaveiro",
      "procuro uma babá",
    ],
    ctaLabel: "Ativar enxame de serviços residenciais",
    processingSteps: [
      "analisando a necessidade...",
      "localizando profissionais disponíveis...",
      "priorizando proximidade...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Diarista" },
      { title: "Cozinheira" },
      { title: "Governanta" },
      { title: "Cuidador de Idosos" },
      { title: "Babá" },
      { title: "Dog Walker" },
      { title: "Pet Sitter" },
      { title: "Jardineiro" },
      { title: "Piscineiro" },
      { title: "Caseiro" },
      { title: "Zelador" },
      { title: "Marido de Aluguel" },
      { title: "Montador de Móveis" },
      { title: "Chaveiro" },
      { title: "Vidraceiro" },
      { title: "Dedetizador" },
      { title: "Técnico de Ar-Condicionado" },
      { title: "Técnico em Eletrodomésticos" },
      { title: "Segurança" },
      { title: "Limpeza de Estofados" },
    ],
    keywords: ["limpeza", "cuidados", "manutenção", "casa"],
    colors: {
      from: "#059669",
      to: "#10b981",
      glow: "rgba(16,185,129,0.45)",
      ring: "rgba(16,185,129,0.7)",
      accent: "#34d399",
      text: "#a7f3d0",
    },
  },
  {
    id: "construcao",
    name: "Enxame de Construção",
    label: "08",
    headline: "Coloque sua obra em movimento.",
    subheadline:
      "Profissionais para construção, reforma, instalações e acabamento.",
    microcopy: "Do reparo à reforma: quem coloca a obra para andar.",
    inputPlaceholder: "Quero reformar",
    rotatingPlaceholders: [
      "preciso de um pedreiro",
      "quero um eletricista",
      "procuro um arquiteto",
      "preciso finalizar acabamento",
    ],
    ctaLabel: "Ativar enxame de construção",
    processingSteps: [
      "interpretando a demanda...",
      "buscando profissionais de obra...",
      "combinando especialidades...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Pedreiro" },
      { title: "Servente de Pedreiro" },
      { title: "Mestre de Obras" },
      { title: "Engenheiro Civil" },
      { title: "Arquiteto" },
      { title: "Marceneiro" },
      { title: "Serralheiro" },
      { title: "Soldador" },
      { title: "Eletricista" },
      { title: "Encanador" },
      { title: "Pintor" },
      { title: "Gesseiro" },
      { title: "Azulejista" },
      { title: "Marmorista" },
      { title: "Vidraceiro" },
      { title: "Telhadista" },
      { title: "Operador de Máquinas Pesadas" },
      { title: "Topógrafo" },
      { title: "Técnico em Segurança" },
      { title: "Designer de Interiores" },
      { title: "Técnico em Energia Solar" },
      { title: "Técnico em Refrigeração" },
      { title: "Técnico de Elevadores" },
      { title: "Demolidor" },
      { title: "Técnico em Saneamento" },
      { title: "Corretor de Imóveis" },
      { title: "Limpeza Pesada" },
      { title: "Construtor" },
    ],
    keywords: ["obra", "reforma", "acabamento", "execução"],
    colors: {
      from: "#ea580c",
      to: "#f97316",
      glow: "rgba(249,115,22,0.45)",
      ring: "rgba(249,115,22,0.7)",
      accent: "#fb923c",
      text: "#fed7aa",
    },
  },
  {
    id: "saude",
    name: "Enxame de Saúde",
    label: "09",
    headline: "Cuide da saúde com quem entende.",
    subheadline:
      "Médicos, terapeutas e profissionais de cuidado para o corpo e a mente.",
    microcopy: "Atenção e cuidado perto de você.",
    inputPlaceholder: "Quero agendar um atendimento",
    rotatingPlaceholders: [
      "quero um fisioterapeuta",
      "procuro um psicólogo",
      "preciso de um cuidador",
      "quero um nutricionista",
    ],
    ctaLabel: "Ativar enxame de saúde",
    processingSteps: [
      "analisando o pedido...",
      "localizando profissionais...",
      "cruzando especialidades...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Médico" },
      { title: "Enfermeiro" },
      { title: "Psiquiatra" },
      { title: "Psicólogo" },
      { title: "Fisioterapeuta" },
      { title: "Fonoaudiólogo" },
      { title: "Nutricionista" },
      { title: "Dentista" },
      { title: "Biomédico" },
      { title: "Farmacêutico" },
      { title: "Radiologista" },
      { title: "Biólogo" },
      { title: "Personal Trainer" },
      { title: "Massoterapeuta" },
      { title: "Quiropraxista" },
      { title: "Acupunturista" },
      { title: "Cuidador de Idosos" },
      { title: "Paramédico" },
      { title: "Condutor de Ambulância" },
      { title: "Médico do Trabalho" },
      { title: "Perito Médico" },
      { title: "Auditor em Saúde" },
      { title: "Podólogo" },
      { title: "Esteticista" },
      { title: "Doula" },
      { title: "Cuidador Infantil" },
      { title: "Protético" },
    ],
    keywords: ["saúde", "terapia", "cuidado", "bem-estar"],
    colors: {
      from: "#0d9488",
      to: "#06b6d4",
      glow: "rgba(6,182,212,0.45)",
      ring: "rgba(6,182,212,0.7)",
      accent: "#22d3ee",
      text: "#a5f3fc",
    },
  },
  {
    id: "beleza_bem_estar",
    name: "Enxame de Beleza e Bem-estar",
    label: "10",
    headline: "Cuide da sua imagem e do seu bem-estar.",
    subheadline:
      "Cabelo, estética, terapias e autocuidado com profissionais perto de você.",
    microcopy: "Do relaxamento à produção: autoestima com gente certa.",
    inputPlaceholder: "Quero agendar um atendimento",
    rotatingPlaceholders: [
      "quero um cabeleireiro",
      "procuro uma manicure",
      "quero uma massagem",
      "quero fazer sobrancelha",
    ],
    ctaLabel: "Ativar enxame de beleza e bem-estar",
    processingSteps: [
      "analisando o pedido...",
      "localizando profissionais...",
      "cruzando especialidades...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Cabeleireiro" },
      { title: "Barbeiro" },
      { title: "Trancista" },
      { title: "Maquiador" },
      { title: "Nail Designer" },
      { title: "Manicure" },
      { title: "Lash Designer" },
      { title: "Micropigmentador" },
      { title: "Esteticista" },
      { title: "Massagista" },
      { title: "Acupunturista" },
      { title: "Terapeuta" },
      { title: "Spa" },
      { title: "Emagrecimento" },
      { title: "Personal Trainer" },
      { title: "Instrutor de Yoga" },
      { title: "Instrutor de Pilates" },
      { title: "Nutricionista" },
      { title: "Tatuador" },
      { title: "Body Piercer" },
      { title: "Harmonização Facial" },
      { title: "Dentista" },
      { title: "Cirurgião Plástico" },
      { title: "Recepcionista" },
      { title: "Revendedor de Cosméticos" },
      { title: "Depilador" },
    ],
    keywords: ["beleza", "estética", "terapias", "autocuidado"],
    colors: {
      from: "#c026d3",
      to: "#d946ef",
      glow: "rgba(217,70,239,0.45)",
      ring: "rgba(217,70,239,0.7)",
      accent: "#e879f9",
      text: "#f5d0fe",
    },
  },
  {
    id: "veiculos",
    name: "Enxame de Veículos",
    label: "11",
    headline: "Seu veículo nas mãos certas.",
    subheadline:
      "Mecânica, estética automotiva, reparos e serviços para todo tipo de veículo.",
    microcopy: "Da revisão ao detalhe: cuidado para o seu veículo.",
    inputPlaceholder: "Preciso de um mecânico",
    rotatingPlaceholders: [
      "preciso de um mecânico",
      "quero um polimento",
      "procuro um borracheiro",
      "quero instalar acessórios",
    ],
    ctaLabel: "Ativar enxame de veículos",
    processingSteps: [
      "analisando o serviço...",
      "localizando especialistas...",
      "priorizando proximidade...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Mecânico Automotivo" },
      { title: "Mecânico de Moto" },
      { title: "Mecânico de Caminhão" },
      { title: "Eletricista Automotivo" },
      { title: "Funileiro" },
      { title: "Martelinho de Ouro" },
      { title: "Detailer Automotivo" },
      { title: "Envelopador Automotivo" },
      { title: "Insulfilm" },
      { title: "Instalador de Acessórios" },
      { title: "Balanceamento e Alinhamento" },
      { title: "Borracheiro" },
      { title: "Chaveiro Automotivo" },
      { title: "Guincheiro" },
      { title: "Vistoriador Veicular" },
      { title: "Consultor Automotivo" },
      { title: "Despachante Veicular" },
      { title: "Corretor de Seguros Automotivos" },
      { title: "Tapeceiro Automotivo" },
      { title: "Mecânico Náutico" },
      { title: "Mecânico de Máquinas Agrícolas" },
      { title: "Instrutor de Direção" },
      { title: "Especialista em Carros Elétricos" },
      { title: "Consultor de Blindagem" },
    ],
    keywords: ["mecânica", "estética automotiva", "reparo", "veículo"],
    colors: {
      from: "#dc2626",
      to: "#ef4444",
      glow: "rgba(239,68,68,0.45)",
      ring: "rgba(239,68,68,0.7)",
      accent: "#f87171",
      text: "#fecaca",
    },
  },
  {
    id: "pets",
    name: "Enxame de Pets",
    label: "12",
    headline: "Seu pet cuidado como merece.",
    subheadline:
      "Veterinária, banho e tosa, adestramento e cuidados para animais.",
    microcopy: "Do banho ao veterinário: rede completa para o seu pet.",
    inputPlaceholder: "Quero cuidar do meu pet",
    rotatingPlaceholders: [
      "quero banho e tosa",
      "procuro um veterinário",
      "preciso de um dog walker",
      "quero um adestrador",
    ],
    ctaLabel: "Ativar enxame de pets",
    processingSteps: [
      "analisando a necessidade...",
      "buscando cuidadores próximos...",
      "selecionando especialistas...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Veterinário" },
      { title: "Auxiliar Veterinário" },
      { title: "Tosador" },
      { title: "Dog Walker" },
      { title: "Pet Sitter" },
      { title: "Adestrador de Cães" },
      { title: "Especialista em Animais Exóticos" },
      { title: "Aquarista" },
      { title: "Criador de Pets" },
      { title: "Modelo Pet" },
      { title: "Vendedor Pet" },
      { title: "Designer de Roupas Pet" },
      { title: "Artesão Pet" },
      { title: "Táxi Pet" },
      { title: "Biólogo Animal" },
      { title: "Especialista em Reprodução Animal" },
      { title: "Tratador Equino" },
    ],
    keywords: ["pet", "banho", "veterinário", "adestramento"],
    colors: {
      from: "#16a34a",
      to: "#22c55e",
      glow: "rgba(34,197,94,0.45)",
      ring: "rgba(34,197,94,0.7)",
      accent: "#4ade80",
      text: "#bbf7d0",
    },
  },
  {
    id: "rural",
    name: "Enxame Rural",
    label: "13",
    headline: "O campo com gente que entende do campo.",
    subheadline:
      "Agropecuária, máquinas, manejo e gestão para a produção rural.",
    microcopy: "Do plantio à colheita: profissionais para o agro.",
    inputPlaceholder: "Preciso de apoio no campo",
    rotatingPlaceholders: [
      "procuro um agrônomo",
      "preciso de um veterinário rural",
      "quero um operador de máquinas",
      "procuro um consultor agro",
    ],
    ctaLabel: "Ativar enxame rural",
    processingSteps: [
      "analisando a demanda...",
      "buscando profissionais do agro...",
      "combinando especialidades...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Produtor Rural" },
      { title: "Pecuarista" },
      { title: "Engenheiro Agrônomo" },
      { title: "Veterinário Rural" },
      { title: "Zootecnista" },
      { title: "Biólogo Rural" },
      { title: "Consultor Agropecuário" },
      { title: "Administrador Rural" },
      { title: "Operador de Máquinas Agrícolas" },
      { title: "Colhedor Rural" },
      { title: "Aplicador de Defensivos Agrícolas" },
      { title: "Piloto de Drone Agrícola" },
      { title: "Floricultor" },
      { title: "Apicultor" },
      { title: "Ordenhador" },
      { title: "Inseminador Animal" },
      { title: "Ferrador" },
      { title: "Nutricionista Animal" },
      { title: "Engenheiro Florestal" },
      { title: "Técnico em Meio Ambiente" },
      { title: "Vendedor de Insumos Agrícolas" },
      { title: "Especialista em Agricultura Orgânica" },
    ],
    keywords: ["agro", "pecuária", "manejo", "campo"],
    colors: {
      from: "#65a30d",
      to: "#84cc16",
      glow: "rgba(132,204,22,0.45)",
      ring: "rgba(132,204,22,0.7)",
      accent: "#a3e635",
      text: "#d9f99d",
    },
  },
  {
    id: "educacao",
    name: "Enxame de Educação",
    label: "14",
    headline: "Aprenda e ensine com quem inspira.",
    subheadline:
      "Professores, mentores e treinadores para desenvolver pessoas.",
    microcopy: "Conhecimento que transforma — em qualquer fase.",
    inputPlaceholder: "Quero um professor ou mentor",
    rotatingPlaceholders: [
      "quero aulas particulares",
      "procuro um mentor",
      "quero um treinador",
      "preciso de reforço escolar",
    ],
    ctaLabel: "Ativar enxame de educação",
    processingSteps: [
      "entendendo o objetivo...",
      "cruzando educadores...",
      "selecionando especialistas...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Professor" },
      { title: "Diretor Escolar" },
      { title: "Orientador Educacional" },
      { title: "Psicopedagogo" },
      { title: "Professor Universitário" },
      { title: "Pesquisador Acadêmico" },
      { title: "Mentor" },
      { title: "Coach" },
      { title: "Palestrante" },
      { title: "Treinador Corporativo" },
      { title: "Revisor Acadêmico" },
      { title: "Professor de Educação Física" },
      { title: "Treinador Esportivo" },
      { title: "Catequista" },
      { title: "Professor de Educação Especial" },
      { title: "Aplicador de Treinamentos Corporativos" },
    ],
    keywords: ["ensino", "mentoria", "treinamento", "aprendizado"],
    colors: {
      from: "#0284c7",
      to: "#0ea5e9",
      glow: "rgba(14,165,233,0.45)",
      ring: "rgba(14,165,233,0.7)",
      accent: "#38bdf8",
      text: "#bae6fd",
    },
  },
  {
    id: "eventos",
    name: "Enxame de Eventos",
    label: "15",
    headline: "Faça seu evento acontecer.",
    subheadline:
      "Produção, gastronomia, animação e estrutura para festas e eventos.",
    microcopy: "Cada detalhe da festa com o profissional certo.",
    inputPlaceholder: "Quero organizar um evento",
    rotatingPlaceholders: [
      "quero um buffet",
      "procuro um DJ",
      "preciso de um cerimonialista",
      "quero um fotógrafo",
    ],
    ctaLabel: "Ativar enxame de eventos",
    processingSteps: [
      "analisando o evento...",
      "cruzando fornecedores...",
      "montando a estrutura...",
      "ativando o enxame...",
    ],
    resultCards: [
      { title: "Produtor de Eventos" },
      { title: "Cerimonialista" },
      { title: "Promoter" },
      { title: "Recepcionista de Eventos" },
      { title: "Locutor" },
      { title: "DJ" },
      { title: "Cantor" },
      { title: "Músico para Eventos" },
      { title: "Animador de Festas" },
      { title: "Mágico" },
      { title: "Bartender" },
      { title: "Garçom" },
      { title: "Chef para Eventos" },
      { title: "Churrasqueiro" },
      { title: "Cake Designer" },
      { title: "Florista" },
      { title: "Fotógrafo de Eventos" },
      { title: "Videomaker de Eventos" },
      { title: "Bombeiro Civil" },
      { title: "Valet" },
      { title: "Motorista Executivo" },
      { title: "Limpeza Pós-Evento" },
      { title: "Staff de Eventos" },
      { title: "Organizador" },
      { title: "Locador de Equipamentos para Eventos" },
    ],
    keywords: ["eventos", "festa", "produção", "gastronomia"],
    colors: {
      from: "#ca8a04",
      to: "#eab308",
      glow: "rgba(234,179,8,0.45)",
      ring: "rgba(234,179,8,0.7)",
      accent: "#facc15",
      text: "#fef08a",
    },
  },
]

export const getMachine = (id: MachineId) =>
  MACHINES.find((m) => m.id === id) as MachineTheme
